version: '3.8'

services:
  # backend:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/user_management
  #     - JDBC_DATABASE_USERNAME=admin
  #     - JDBC_DATABASE_PASSWORD=Password@123
  #   ports:
  #     - "8081:8080"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@123
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
# volumes:
#   db_data:
